---
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then pip install black; fi
  - pip install -r requirements/dev.txt -r requirements/docs.txt
  - python setup.py install
  - pip install .[ssh2]
  - pip install .[paramiko]

script:
  - |
    if [[ "$TRAVIS_PYTHON_VERSION" == "3.6" ]]; then
      black --exclude harbinger/exc --check --diff -l 79 *.py harbinger docs
    fi
  - yamllint .travis.yml
  - flake8 *.py harbinger docs
  - nosetests
  - make -C docs html
